"""Narada platform catalog — the FULL list of integrations Narada
*plans* to support, generated 2026-07-02 from
docs/narada/narada-signup-checklist.xlsx (111 tools, 16 categories).

This is DATA ONLY — no implementation code. The narada_plugins/
directory holds actual working plugin classes (~10 shipped). This
catalog augments those in the UI so users can see the full
platform breadth even for tools we haven't coded plugins for yet.

Rendering rule:
  - Tools with a live plugin (info().name matches a slug here):
    live plugin wins, show paste-key form + Save button.
  - Tools without a live plugin: show "coming soon" badge +
    signup URL + description. No paste form (nothing to store
    against yet).
"""
from __future__ import annotations

NARADA_PLATFORM_CATALOG = [
  {
    "slug": "hubspot",
    "display_name": "HubSpot",
    "raw_category": "CRM",
    "category": "CRM",
    "homepage": "https://app.hubspot.com/signup-hubspot",
    "description": "Most popular for SMB. Recommend via Composio — one OAuth.",
    "priority": "Tier 1",
    "free_tier": "Free CRM tier",
    "paid_price": "$20+/mo",
    "key_location_hint": "Use Composio (recommended) OR Settings → Integrations → Private Apps"
  },
  {
    "slug": "google_calendar",
    "display_name": "Google Calendar",
    "raw_category": "Calendar",
    "category": "CALENDAR",
    "homepage": "(via Composio — already covered)",
    "description": "Use the Composio auth config; no separate signup.",
    "priority": "Tier 1",
    "free_tier": "Bundled with Workspace",
    "paid_price": "Bundled",
    "key_location_hint": "Composio auth config for googlecalendar app"
  },
  {
    "slug": "google_postmaster_tools",
    "display_name": "Google Postmaster Tools",
    "raw_category": "Deliverability",
    "category": "DELIVERABILITY",
    "homepage": "https://postmaster.google.com/",
    "description": "MUST-HAVE for any domain sending to Gmail addresses. Shows spam rate, reputation, DKIM/SPF/DMARC compliance.",
    "priority": "Tier 1",
    "free_tier": "Free",
    "paid_price": "Free",
    "key_location_hint": "Dashboard after domain verification"
  },
  {
    "slug": "mail-tester.com",
    "display_name": "Mail-tester.com",
    "raw_category": "Deliverability",
    "category": "DELIVERABILITY",
    "homepage": "(no signup needed)",
    "description": "Instant one-off spam-score check. Bookmark this.",
    "priority": "Tier 1",
    "free_tier": "Free (one test at a time)",
    "paid_price": "$25/mo for saved history",
    "key_location_hint": "Just send an email to the address on their homepage"
  },
  {
    "slug": "prospeo",
    "display_name": "Prospeo",
    "raw_category": "Lead source + Verifier",
    "category": "LEAD_SOURCE",
    "homepage": "https://prospeo.io/auth/register",
    "description": "Already chosen for v1. Does both lead search AND email verify from one subscription.",
    "priority": "Tier 1",
    "free_tier": "Free 100 credits/mo",
    "paid_price": "$37/mo Starter (2K credits)",
    "key_location_hint": "Dashboard → Settings → API → Generate Key"
  },
  {
    "slug": "composio",
    "display_name": "Composio",
    "raw_category": "OAuth substrate",
    "category": "OAUTH",
    "homepage": "https://app.composio.dev/sign-up",
    "description": "Gets you Gmail + HubSpot + Salesforce + Calendar + Slack + GitHub + Notion + 1000 more via one OAuth flow. Create auth configs for: gmail, googlecalendar, hubspot, salesforce, pipedrive, slack, github, notion.",
    "priority": "Tier 1",
    "free_tier": "Free tier covers most apps",
    "paid_price": "$99/mo Pro",
    "key_location_hint": "Dashboard → API Keys → Generate + Auth Configs (one per app)"
  },
  {
    "slug": "neverbounce",
    "display_name": "NeverBounce",
    "raw_category": "Verifier",
    "category": "VERIFIER",
    "homepage": "https://app.neverbounce.com/register",
    "description": "Independent verifier alongside Prospeo — double-check before send.",
    "priority": "Tier 1",
    "free_tier": "Free trial 1K verifications",
    "paid_price": "Pay-as-you-go from $0.008/verify",
    "key_location_hint": "Dashboard → API → API Key"
  },
  {
    "slug": "meta_whatsapp_cloud_api",
    "display_name": "Meta WhatsApp Cloud API",
    "raw_category": "WhatsApp",
    "category": "WHATSAPP",
    "homepage": "https://developers.facebook.com/docs/whatsapp/cloud-api/get-started",
    "description": "OFFICIAL, cheapest at scale. Requires Meta Business + verified phone. Template-message-based for cold.",
    "priority": "Tier 1",
    "free_tier": "Free up to 1K conversations/mo",
    "paid_price": "Pay per conversation",
    "key_location_hint": "Meta Business Suite → WhatsApp → API access token"
  },
  {
    "slug": "posthog",
    "display_name": "PostHog",
    "raw_category": "Analytics",
    "category": "ANALYTICS",
    "homepage": "https://us.posthog.com/signup",
    "description": "Open source, self-hostable. Recommended default.",
    "priority": "Tier 2",
    "free_tier": "1M events/mo free",
    "paid_price": "$0-$45/mo",
    "key_location_hint": "Project → Settings → API Keys"
  },
  {
    "slug": "close",
    "display_name": "Close",
    "raw_category": "CRM",
    "category": "CRM",
    "homepage": "https://app.close.com/signup/",
    "description": "Built specifically for outbound. Native call + email.",
    "priority": "Tier 2",
    "free_tier": "14-day trial",
    "paid_price": "$29/user/mo",
    "key_location_hint": "Settings → Developer → API Keys"
  },
  {
    "slug": "pipedrive",
    "display_name": "Pipedrive",
    "raw_category": "CRM",
    "category": "CRM",
    "homepage": "https://www.pipedrive.com/en/register",
    "description": "SDR-friendly pipeline visuals.",
    "priority": "Tier 2",
    "free_tier": "14-day trial",
    "paid_price": "$14/user/mo",
    "key_location_hint": "Use Composio OR Settings → Personal preferences → API"
  },
  {
    "slug": "salesforce",
    "display_name": "Salesforce",
    "raw_category": "CRM",
    "category": "CRM",
    "homepage": "https://www.salesforce.com/form/signup/freetrial-sales/",
    "description": "Enterprise standard. Via Composio for OAuth simplicity.",
    "priority": "Tier 2",
    "free_tier": "30-day trial only",
    "paid_price": "$25/user/mo",
    "key_location_hint": "Use Composio OR Setup → Apps → App Manager → New Connected App"
  },
  {
    "slug": "cal.com",
    "display_name": "Cal.com",
    "raw_category": "Calendar",
    "category": "CALENDAR",
    "homepage": "https://app.cal.com/signup",
    "description": "Open source alternative to Calendly. Self-hostable.",
    "priority": "Tier 2",
    "free_tier": "Free tier",
    "paid_price": "$15/seat/mo Teams",
    "key_location_hint": "Settings → Developer → API Keys"
  },
  {
    "slug": "calendly",
    "display_name": "Calendly",
    "raw_category": "Calendar",
    "category": "CALENDAR",
    "homepage": "https://calendly.com/signup",
    "description": "Most popular public-booking link tool.",
    "priority": "Tier 2",
    "free_tier": "Free tier",
    "paid_price": "$10/seat/mo for API access",
    "key_location_hint": "Integrations → API & Webhooks"
  },
  {
    "slug": "outlook_calendar",
    "display_name": "Outlook Calendar",
    "raw_category": "Calendar",
    "category": "CALENDAR",
    "homepage": "(via Composio — already covered)",
    "description": "Same as Google Calendar path.",
    "priority": "Tier 2",
    "free_tier": "Bundled with M365",
    "paid_price": "Bundled",
    "key_location_hint": "Composio auth config for outlook_calendar app"
  },
  {
    "slug": "glockapps",
    "display_name": "GlockApps",
    "raw_category": "Deliverability",
    "category": "DELIVERABILITY",
    "homepage": "https://app.glockapps.com/signup",
    "description": "Inbox placement testing across Gmail/Outlook/Yahoo.",
    "priority": "Tier 2",
    "free_tier": "Free 3 spam tests",
    "paid_price": "$59/mo Personal",
    "key_location_hint": "Dashboard → API"
  },
  {
    "slug": "mxtoolbox",
    "display_name": "MXToolbox",
    "raw_category": "Deliverability",
    "category": "DELIVERABILITY",
    "homepage": "https://mxtoolbox.com/user/signup",
    "description": "DNS diagnostics, blacklist checks. Free tier is plenty for spot checks.",
    "priority": "Tier 2",
    "free_tier": "Free for DNS/blacklist checks",
    "paid_price": "$149/mo for monitoring",
    "key_location_hint": "Dashboard"
  },
  {
    "slug": "microsoft_snds",
    "display_name": "Microsoft SNDS",
    "raw_category": "Deliverability",
    "category": "DELIVERABILITY",
    "homepage": "https://sendersupport.olc.protection.outlook.com/snds/",
    "description": "Same as Postmaster but for Outlook/Hotmail domains.",
    "priority": "Tier 2",
    "free_tier": "Free",
    "paid_price": "Free",
    "key_location_hint": "Register your sending IPs"
  },
  {
    "slug": "builtwith",
    "display_name": "BuiltWith",
    "raw_category": "Enrichment",
    "category": "ENRICHMENT",
    "homepage": "https://api.builtwith.com/signup",
    "description": "Tech-stack signals ('uses Stripe + Segment') — great for intent-based targeting.",
    "priority": "Tier 2",
    "free_tier": "Free lookup tier",
    "paid_price": "$295/mo for bulk",
    "key_location_hint": "Dashboard → API Keys"
  },
  {
    "slug": "clearbit_hubspot_breeze",
    "display_name": "Clearbit (HubSpot Breeze)",
    "raw_category": "Enrichment",
    "category": "ENRICHMENT",
    "homepage": "https://app.hubspot.com/signup-hubspot/breeze-intelligence",
    "description": "Now part of HubSpot's Breeze suite. Company + person enrichment.",
    "priority": "Tier 2",
    "free_tier": "Bundled with paid HubSpot",
    "paid_price": "$100/mo add-on",
    "key_location_hint": "Via HubSpot → Breeze Intelligence"
  },
  {
    "slug": "crunchbase",
    "display_name": "Crunchbase",
    "raw_category": "Enrichment",
    "category": "ENRICHMENT",
    "homepage": "https://www.crunchbase.com/pricing",
    "description": "Funding/news/exec-change data.",
    "priority": "Tier 2",
    "free_tier": "None (Pro required for API)",
    "paid_price": "$99/mo Pro",
    "key_location_hint": "Account → API (requires Pro)"
  },
  {
    "slug": "lix",
    "display_name": "Lix",
    "raw_category": "Enrichment",
    "category": "ENRICHMENT",
    "homepage": "https://lix-it.com/signup",
    "description": "Cheap LinkedIn enrichment. Good complement to Prospeo.",
    "priority": "Tier 2",
    "free_tier": "None",
    "paid_price": "$39/mo Starter",
    "key_location_hint": "Dashboard → API"
  },
  {
    "slug": "clay",
    "display_name": "Clay",
    "raw_category": "Lead source",
    "category": "LEAD_SOURCE",
    "homepage": "https://app.clay.com/signup",
    "description": "The 'ETL of prospecting' — combines 50+ data sources. Agency favourite. Expensive but replaces many other tools.",
    "priority": "Tier 2",
    "free_tier": "14-day trial",
    "paid_price": "$149/mo Starter",
    "key_location_hint": "Workspace → API"
  },
  {
    "slug": "findymail",
    "display_name": "FindyMail",
    "raw_category": "Lead source",
    "category": "LEAD_SOURCE",
    "homepage": "https://app.findymail.com/register",
    "description": "Cheap LinkedIn URL → email lookup. Used heavily by agencies for bulk.",
    "priority": "Tier 2",
    "free_tier": "No free tier",
    "paid_price": "$49/mo Starter",
    "key_location_hint": "Dashboard → API tokens"
  },
  {
    "slug": "hunter",
    "display_name": "Hunter",
    "raw_category": "Lead source",
    "category": "LEAD_SOURCE",
    "homepage": "https://hunter.io/users/sign_up",
    "description": "Cheapest email-finder. Verify bundled — could replace NeverBounce.",
    "priority": "Tier 2",
    "free_tier": "Free 25 searches + 50 verifications/mo",
    "paid_price": "$49/mo Starter",
    "key_location_hint": "Dashboard → API"
  },
  {
    "slug": "rocketreach",
    "display_name": "RocketReach",
    "raw_category": "Lead source",
    "category": "LEAD_SOURCE",
    "homepage": "https://rocketreach.co/signup",
    "description": "Strong on personal email + at-any-company reach.",
    "priority": "Tier 2",
    "free_tier": "Free 5 lookups",
    "paid_price": "$99/mo Essentials",
    "key_location_hint": "Account → API"
  },
  {
    "slug": "apollo.io",
    "display_name": "Apollo.io",
    "raw_category": "Lead source + Sender",
    "category": "LEAD_SOURCE",
    "homepage": "https://app.apollo.io/#/signup",
    "description": "Combines leads + sequences in one vendor. Note: API access is 'on Custom plans' per docs — may need to call sales.",
    "priority": "Tier 2",
    "free_tier": "Free 900 credits/yr",
    "paid_price": "$49/seat/mo Basic",
    "key_location_hint": "Settings → Integrations → API"
  },
  {
    "slug": "heyreach",
    "display_name": "Heyreach",
    "raw_category": "LinkedIn",
    "category": "LINKEDIN",
    "homepage": "https://app.heyreach.io/signup",
    "description": "Most popular agency LinkedIn tool. Multi-account safe.",
    "priority": "Tier 2",
    "free_tier": "7-day trial",
    "paid_price": "$79/mo Starter",
    "key_location_hint": "Workspace → API"
  },
  {
    "slug": "phantombuster",
    "display_name": "Phantombuster",
    "raw_category": "LinkedIn + Scraping",
    "category": "LINKEDIN",
    "homepage": "https://phantombuster.com/signup",
    "description": "Most flexible — can scrape almost anything. LinkedIn Phantoms + custom automations.",
    "priority": "Tier 2",
    "free_tier": "14-day trial",
    "paid_price": "$69/mo Starter",
    "key_location_hint": "Account → API Key"
  },
  {
    "slug": "emailbison",
    "display_name": "EmailBison",
    "raw_category": "Sender",
    "category": "SENDER",
    "homepage": "https://app.emailbison.com/register",
    "description": "The @harsh_biz tweet author's pick. Called it 'the sickest API' — worth trying if the others don't fit.",
    "priority": "Tier 2",
    "free_tier": "Trial varies",
    "paid_price": "Pricing on request",
    "key_location_hint": "Dashboard → Account → API"
  },
  {
    "slug": "instantly",
    "display_name": "Instantly",
    "raw_category": "Sender",
    "category": "SENDER",
    "homepage": "https://app.instantly.ai/auth/sign-up",
    "description": "Strong warmup pool. API tier-gating unclear; may need Scale ($194).",
    "priority": "Tier 2",
    "free_tier": "Free tier limited",
    "paid_price": "$94/mo Starter, $194/mo Scale",
    "key_location_hint": "Settings → Integrations → API Keys"
  },
  {
    "slug": "lemlist",
    "display_name": "Lemlist",
    "raw_category": "Sender",
    "category": "SENDER",
    "homepage": "https://app.lemlist.com/signup",
    "description": "API on every paid tier — cheapest path to SaaS sender API. Lemwarm warmup bundled.",
    "priority": "Tier 2",
    "free_tier": "14-day trial",
    "paid_price": "$69/mo Email plan",
    "key_location_hint": "Dashboard → Settings → Integrations → API"
  },
  {
    "slug": "smartlead",
    "display_name": "Smartlead",
    "raw_category": "Sender",
    "category": "SENDER",
    "homepage": "https://app.smartlead.ai/auth/sign-up",
    "description": "Industry standard cold email SaaS. Throwaway-domain rotation, warmup pool, sequences. API only from Unlimited Smart tier.",
    "priority": "Tier 2",
    "free_tier": "14-day trial",
    "paid_price": "$174/mo Unlimited Smart (API tier)",
    "key_location_hint": "Dashboard → Settings → API & Webhooks"
  },
  {
    "slug": "twilio_voice",
    "display_name": "Twilio Voice",
    "raw_category": "Voice",
    "category": "VOICE",
    "homepage": "https://www.twilio.com/try-twilio",
    "description": "Cheapest entry to programmable voice. DIY substrate.",
    "priority": "Tier 2",
    "free_tier": "$15 free trial",
    "paid_price": "Pay per minute",
    "key_location_hint": "Console → Voice → API Keys (same account as WA)"
  },
  {
    "slug": "twilio_whatsapp",
    "display_name": "Twilio WhatsApp",
    "raw_category": "WhatsApp",
    "category": "WHATSAPP",
    "homepage": "https://www.twilio.com/try-twilio",
    "description": "Most mature wrapper around Meta's API. Good docs. Two-way messaging support.",
    "priority": "Tier 2",
    "free_tier": "$15 free trial credit",
    "paid_price": "Pay per message",
    "key_location_hint": "Console → Messaging → WhatsApp"
  },
  {
    "slug": "wati",
    "display_name": "Wati",
    "raw_category": "WhatsApp",
    "category": "WHATSAPP",
    "homepage": "https://app.wati.io/register",
    "description": "India-focused. Easy onboarding. Growing fast.",
    "priority": "Tier 2",
    "free_tier": "7-day trial",
    "paid_price": "$39/mo Starter",
    "key_location_hint": "Dashboard → API Docs"
  },
  {
    "slug": "amplitude",
    "display_name": "Amplitude",
    "raw_category": "Analytics",
    "category": "ANALYTICS",
    "homepage": "https://amplitude.com/get-started",
    "description": "Strong cohort analysis.",
    "priority": "Tier 3",
    "free_tier": "10M events/mo free",
    "paid_price": "$49/mo Growth",
    "key_location_hint": "Project → Settings → API Keys"
  },
  {
    "slug": "heap",
    "display_name": "Heap",
    "raw_category": "Analytics",
    "category": "ANALYTICS",
    "homepage": "https://heap.io/sign-up",
    "description": "Auto-capture (no manual event tracking).",
    "priority": "Tier 3",
    "free_tier": "10K sessions/mo free",
    "paid_price": "Custom pricing",
    "key_location_hint": "Account → App Settings → API"
  },
  {
    "slug": "june.so",
    "display_name": "June.so",
    "raw_category": "Analytics",
    "category": "ANALYTICS",
    "homepage": "https://app.june.so/sign-up",
    "description": "B2B-specific dashboards.",
    "priority": "Tier 3",
    "free_tier": "5K events/mo free",
    "paid_price": "$149/mo",
    "key_location_hint": "Workspace → API"
  },
  {
    "slug": "mixpanel",
    "display_name": "Mixpanel",
    "raw_category": "Analytics",
    "category": "ANALYTICS",
    "homepage": "https://mixpanel.com/register/",
    "description": "Standard event analytics.",
    "priority": "Tier 3",
    "free_tier": "100K events/mo free",
    "paid_price": "$25/mo Growth",
    "key_location_hint": "Project → Access Keys"
  },
  {
    "slug": "segment",
    "display_name": "Segment",
    "raw_category": "Analytics",
    "category": "ANALYTICS",
    "homepage": "https://app.segment.com/signup/",
    "description": "Event router — sends to all the others.",
    "priority": "Tier 3",
    "free_tier": "Free dev tier",
    "paid_price": "$120/mo Team",
    "key_location_hint": "Sources → API Keys"
  },
  {
    "slug": "attio",
    "display_name": "Attio",
    "raw_category": "CRM",
    "category": "CRM",
    "homepage": "https://app.attio.com/welcome",
    "description": "Modern, Notion-like. Newer entrant.",
    "priority": "Tier 3",
    "free_tier": "Free tier",
    "paid_price": "$29/user/mo Plus",
    "key_location_hint": "Settings → Developers → API Keys"
  },
  {
    "slug": "copper",
    "display_name": "Copper",
    "raw_category": "CRM",
    "category": "CRM",
    "homepage": "https://app.copper.com/signup",
    "description": "Native Gmail integration — good if Workspace-heavy.",
    "priority": "Tier 3",
    "free_tier": "14-day trial",
    "paid_price": "$29/user/mo Basic",
    "key_location_hint": "Settings → Integrations → API"
  },
  {
    "slug": "folk",
    "display_name": "Folk",
    "raw_category": "CRM",
    "category": "CRM",
    "homepage": "https://app.folk.app/signup",
    "description": "Lightweight, contact-first CRM.",
    "priority": "Tier 3",
    "free_tier": "Free tier",
    "paid_price": "$29/mo Standard",
    "key_location_hint": "Settings → API & Integrations"
  },
  {
    "slug": "monday_sales_crm",
    "display_name": "Monday Sales CRM",
    "raw_category": "CRM",
    "category": "CRM",
    "homepage": "https://auth.monday.com/users/sign_up",
    "description": "Only if you already use Monday for other things.",
    "priority": "Tier 3",
    "free_tier": "14-day trial",
    "paid_price": "$10/seat/mo Basic",
    "key_location_hint": "Admin → API → Generate Token"
  },
  {
    "slug": "zoho_crm",
    "display_name": "Zoho CRM",
    "raw_category": "CRM",
    "category": "CRM",
    "homepage": "https://www.zoho.com/crm/signup.html",
    "description": "Cheap enterprise alternative.",
    "priority": "Tier 3",
    "free_tier": "Free 3-user tier",
    "paid_price": "$14/user/mo Standard",
    "key_location_hint": "Setup → Developer Space → API"
  },
  {
    "slug": "acuity_scheduling",
    "display_name": "Acuity Scheduling",
    "raw_category": "Calendar",
    "category": "CALENDAR",
    "homepage": "https://secure.acuityscheduling.com/signup.php",
    "description": "Service-business focused. Owned by Squarespace.",
    "priority": "Tier 3",
    "free_tier": "7-day trial",
    "paid_price": "$20/mo Emerging",
    "key_location_hint": "Integrations → API"
  },
  {
    "slug": "chili_piper",
    "display_name": "Chili Piper",
    "raw_category": "Calendar",
    "category": "CALENDAR",
    "homepage": "https://www.chilipiper.com/get-a-demo",
    "description": "Round-robin SDR routing. Enterprise-only.",
    "priority": "Tier 3",
    "free_tier": "No self-serve",
    "paid_price": "Enterprise",
    "key_location_hint": "After sales call"
  },
  {
    "slug": "savvycal",
    "display_name": "SavvyCal",
    "raw_category": "Calendar",
    "category": "CALENDAR",
    "homepage": "https://savvycal.com/users/sign_up",
    "description": "Founder-friendly, lightweight.",
    "priority": "Tier 3",
    "free_tier": "None",
    "paid_price": "$12/mo Basic",
    "key_location_hint": "Settings → Integrations"
  },
  {
    "slug": "tidycal",
    "display_name": "TidyCal",
    "raw_category": "Calendar",
    "category": "CALENDAR",
    "homepage": "https://tidycal.com/register",
    "description": "One-time payment. Cheap forever.",
    "priority": "Tier 3",
    "free_tier": "None",
    "paid_price": "$39 one-time (AppSumo)",
    "key_location_hint": "Settings → API"
  },
  {
    "slug": "youcanbookme",
    "display_name": "YouCanBookMe",
    "raw_category": "Calendar",
    "category": "CALENDAR",
    "homepage": "https://youcanbook.me/sign-up",
    "description": "Cheaper Calendly alternative.",
    "priority": "Tier 3",
    "free_tier": "Free tier",
    "paid_price": "$12/mo Pro",
    "key_location_hint": "Dashboard"
  },
  {
    "slug": "litmus",
    "display_name": "Litmus",
    "raw_category": "Deliverability",
    "category": "DELIVERABILITY",
    "homepage": "https://litmus.com/signup",
    "description": "Email rendering + spam testing. Enterprise-focused.",
    "priority": "Tier 3",
    "free_tier": "7-day trial",
    "paid_price": "$99/mo Basic",
    "key_location_hint": "Dashboard → Integrations → API"
  },
  {
    "slug": "owler",
    "display_name": "Owler",
    "raw_category": "Enrichment",
    "category": "ENRICHMENT",
    "homepage": "https://www.owler.com/login",
    "description": "Company news, exec changes.",
    "priority": "Tier 3",
    "free_tier": "Free tier",
    "paid_price": "$35/user/mo Pro",
    "key_location_hint": "Account → API"
  },
  {
    "slug": "similarweb",
    "display_name": "SimilarWeb",
    "raw_category": "Enrichment",
    "category": "ENRICHMENT",
    "homepage": "https://www.similarweb.com/corp/contact-us/",
    "description": "Traffic + competitive intel.",
    "priority": "Tier 3",
    "free_tier": "No self-serve API",
    "paid_price": "Enterprise",
    "key_location_hint": "After sales call"
  },
  {
    "slug": "cognism",
    "display_name": "Cognism",
    "raw_category": "Lead source",
    "category": "LEAD_SOURCE",
    "homepage": "https://www.cognism.com/contact",
    "description": "EU/GDPR-focused. Skip unless European lists are core to your ICP.",
    "priority": "Tier 3",
    "free_tier": "No",
    "paid_price": "Enterprise-only",
    "key_location_hint": "After sales call — no self-serve API tier"
  },
  {
    "slug": "lusha",
    "display_name": "Lusha",
    "raw_category": "Lead source",
    "category": "LEAD_SOURCE",
    "homepage": "https://www.lusha.com/signup/",
    "description": "Strong on mobile numbers + LinkedIn enrichment.",
    "priority": "Tier 3",
    "free_tier": "Free 5 contacts/mo",
    "paid_price": "$74/mo Pro",
    "key_location_hint": "Dashboard → API"
  },
  {
    "slug": "uplead",
    "display_name": "UpLead",
    "raw_category": "Lead source",
    "category": "LEAD_SOURCE",
    "homepage": "https://app.uplead.com/signup",
    "description": "Verified-only data. Lower volume, higher quality.",
    "priority": "Tier 3",
    "free_tier": "7-day trial",
    "paid_price": "$99/mo Essentials",
    "key_location_hint": "Settings → API"
  },
  {
    "slug": "zoominfo",
    "display_name": "ZoomInfo",
    "raw_category": "Lead source",
    "category": "LEAD_SOURCE",
    "homepage": "https://www.zoominfo.com/contact-zoominfo-sales",
    "description": "Largest DB but expensive + long sales cycle. Skip unless you're already using them.",
    "priority": "Tier 3",
    "free_tier": "No",
    "paid_price": "Enterprise-only",
    "key_location_hint": "After sales call — no self-serve API tier"
  },
  {
    "slug": "dripify",
    "display_name": "Dripify",
    "raw_category": "LinkedIn",
    "category": "LINKEDIN",
    "homepage": "https://app.dripify.io/signup",
    "description": "Strong sequence builder.",
    "priority": "Tier 3",
    "free_tier": "No free tier",
    "paid_price": "$59/mo Basic",
    "key_location_hint": "Settings → API"
  },
  {
    "slug": "expandi",
    "display_name": "Expandi",
    "raw_category": "LinkedIn",
    "category": "LINKEDIN",
    "homepage": "https://app.expandi.io/login",
    "description": "Cloud-based (no browser extension needed).",
    "priority": "Tier 3",
    "free_tier": "7-day trial",
    "paid_price": "$99/mo Business",
    "key_location_hint": "Settings → Integrations → API"
  },
  {
    "slug": "la_growth_machine",
    "display_name": "La Growth Machine",
    "raw_category": "LinkedIn",
    "category": "LINKEDIN",
    "homepage": "https://app.lagrowthmachine.com/signup",
    "description": "Multi-channel (LinkedIn + email + Twitter).",
    "priority": "Tier 3",
    "free_tier": "14-day trial",
    "paid_price": "$60/mo Basic",
    "key_location_hint": "Settings → API"
  },
  {
    "slug": "linked_helper",
    "display_name": "Linked Helper",
    "raw_category": "LinkedIn",
    "category": "LINKEDIN",
    "homepage": "https://lib.linkedhelper.com/register",
    "description": "Desktop app; runs on your machine (avoids cloud detection).",
    "priority": "Tier 3",
    "free_tier": "14-day trial",
    "paid_price": "$15/mo Standard",
    "key_location_hint": "Local desktop app; no cloud API"
  },
  {
    "slug": "skylead",
    "display_name": "Skylead",
    "raw_category": "LinkedIn",
    "category": "LINKEDIN",
    "homepage": "https://app.skylead.io/signup",
    "description": "Smart sequences with email fallback.",
    "priority": "Tier 3",
    "free_tier": "7-day trial",
    "paid_price": "$100/mo Individual",
    "key_location_hint": "Settings → Integrations"
  },
  {
    "slug": "waalaxy",
    "display_name": "Waalaxy",
    "raw_category": "LinkedIn",
    "category": "LINKEDIN",
    "homepage": "https://app.waalaxy.com/auth/register",
    "description": "Chrome extension, freemium.",
    "priority": "Tier 3",
    "free_tier": "Free tier limited",
    "paid_price": "$21/mo Advanced",
    "key_location_hint": "No public API on free; paid plans have one"
  },
  {
    "slug": "we-connect",
    "display_name": "We-Connect",
    "raw_category": "LinkedIn",
    "category": "LINKEDIN",
    "homepage": "https://www.we-connect.io/sign-up",
    "description": "Enterprise-friendly, multi-seat.",
    "priority": "Tier 3",
    "free_tier": "14-day trial",
    "paid_price": "$79/mo Standard",
    "key_location_hint": "Account → API"
  },
  {
    "slug": "bouncer",
    "display_name": "Bouncer",
    "raw_category": "Verifier",
    "category": "VERIFIER",
    "homepage": "https://app.usebouncer.com/register",
    "description": "EU-friendly, GDPR-compliant.",
    "priority": "Tier 3",
    "free_tier": "Free 100 credits",
    "paid_price": "$24 for 5K one-time",
    "key_location_hint": "Settings → API"
  },
  {
    "slug": "debounce",
    "display_name": "DeBounce",
    "raw_category": "Verifier",
    "category": "VERIFIER",
    "homepage": "https://app.debounce.io/register",
    "description": "Cheap pay-as-you-go.",
    "priority": "Tier 3",
    "free_tier": "Free 100",
    "paid_price": "$10 for 5K one-time",
    "key_location_hint": "Profile → API"
  },
  {
    "slug": "emaillistverify",
    "display_name": "EmailListVerify",
    "raw_category": "Verifier",
    "category": "VERIFIER",
    "homepage": "https://app.emaillistverify.com/login",
    "description": "Cheapest overall. Free tier is generous.",
    "priority": "Tier 3",
    "free_tier": "Free 1K/day",
    "paid_price": "$4 for 1K one-time",
    "key_location_hint": "Account → API"
  },
  {
    "slug": "mailercheck",
    "display_name": "MailerCheck",
    "raw_category": "Verifier",
    "category": "VERIFIER",
    "homepage": "https://app.mailercheck.com/signup",
    "description": "Made by MailerLite team.",
    "priority": "Tier 3",
    "free_tier": "None (trial only)",
    "paid_price": "$10 for 1K",
    "key_location_hint": "Settings → API"
  },
  {
    "slug": "millionverifier",
    "display_name": "MillionVerifier",
    "raw_category": "Verifier",
    "category": "VERIFIER",
    "homepage": "https://app.millionverifier.com/signup",
    "description": "Cheapest at scale.",
    "priority": "Tier 3",
    "free_tier": "No free tier",
    "paid_price": "$9 for 1K (one-time)",
    "key_location_hint": "Account → API"
  },
  {
    "slug": "zerobounce",
    "display_name": "ZeroBounce",
    "raw_category": "Verifier",
    "category": "VERIFIER",
    "homepage": "https://www.zerobounce.net/members/signup",
    "description": "Bulk verification. Catch-all detection.",
    "priority": "Tier 3",
    "free_tier": "Free 100 credits/mo",
    "paid_price": "$16 for 2K one-time",
    "key_location_hint": "Dashboard → API → Keys"
  },
  {
    "slug": "aircall",
    "display_name": "AirCall",
    "raw_category": "Voice",
    "category": "VOICE",
    "homepage": "https://aircall.io/contact-sales/",
    "description": "Industry-standard cloud phone. Talk to sales.",
    "priority": "Tier 3",
    "free_tier": "No self-serve",
    "paid_price": "Enterprise",
    "key_location_hint": "After sales call"
  },
  {
    "slug": "aloware",
    "display_name": "Aloware",
    "raw_category": "Voice",
    "category": "VOICE",
    "homepage": "https://www.aloware.com/signup/",
    "description": "Cloud contact centre.",
    "priority": "Tier 3",
    "free_tier": "14-day trial",
    "paid_price": "$30/user/mo",
    "key_location_hint": "Settings → API"
  },
  {
    "slug": "dialpad",
    "display_name": "Dialpad",
    "raw_category": "Voice",
    "category": "VOICE",
    "homepage": "https://www.dialpad.com/sign-up/",
    "description": "AI transcription bundled.",
    "priority": "Tier 3",
    "free_tier": "14-day trial",
    "paid_price": "$15/user/mo Standard",
    "key_location_hint": "Admin → Integrations → API"
  },
  {
    "slug": "justcall",
    "display_name": "JustCall",
    "raw_category": "Voice",
    "category": "VOICE",
    "homepage": "https://app.justcall.io/signup",
    "description": "Affordable multi-channel.",
    "priority": "Tier 3",
    "free_tier": "14-day trial",
    "paid_price": "$24/user/mo Essentials",
    "key_location_hint": "Settings → Developer → API Keys"
  },
  {
    "slug": "kixie",
    "display_name": "Kixie",
    "raw_category": "Voice",
    "category": "VOICE",
    "homepage": "https://app.kixie.com/signup",
    "description": "Built for outbound SDR.",
    "priority": "Tier 3",
    "free_tier": "7-day trial",
    "paid_price": "$35/user/mo Integrated",
    "key_location_hint": "Settings → API"
  },
  {
    "slug": "nooks",
    "display_name": "Nooks",
    "raw_category": "Voice",
    "category": "VOICE",
    "homepage": "https://nooks.ai/get-a-demo",
    "description": "Modern parallel dialer.",
    "priority": "Tier 3",
    "free_tier": "No self-serve",
    "paid_price": "Enterprise",
    "key_location_hint": "After sales call"
  },
  {
    "slug": "orum",
    "display_name": "Orum",
    "raw_category": "Voice",
    "category": "VOICE",
    "homepage": "https://orum.com/request-demo",
    "description": "AI parallel dialer. Enterprise SDR tool.",
    "priority": "Tier 3",
    "free_tier": "No self-serve",
    "paid_price": "Enterprise",
    "key_location_hint": "After sales call"
  },
  {
    "slug": "phoneburner",
    "display_name": "PhoneBurner",
    "raw_category": "Voice",
    "category": "VOICE",
    "homepage": "https://app.phoneburner.com/signup",
    "description": "Power dialer focus.",
    "priority": "Tier 3",
    "free_tier": "None",
    "paid_price": "$149/user/mo Standard",
    "key_location_hint": "Account → API"
  },
  {
    "slug": "allegrow",
    "display_name": "Allegrow",
    "raw_category": "Warmup",
    "category": "WARMUP",
    "homepage": "https://app.allegrow.co/signup",
    "description": "Focus on inbox placement, not just warmup.",
    "priority": "Tier 3",
    "free_tier": "None",
    "paid_price": "$25/mailbox/mo",
    "key_location_hint": "Dashboard"
  },
  {
    "slug": "folderly",
    "display_name": "Folderly",
    "raw_category": "Warmup",
    "category": "WARMUP",
    "homepage": "https://app.folderly.com/sign-up",
    "description": "Warmup + continuous deliverability monitoring. Enterprise pricing.",
    "priority": "Tier 3",
    "free_tier": "Trial",
    "paid_price": "$200/mailbox/mo",
    "key_location_hint": "Dashboard"
  },
  {
    "slug": "mailreach",
    "display_name": "Mailreach",
    "raw_category": "Warmup",
    "category": "WARMUP",
    "homepage": "https://app.mailreach.co/users/sign_up",
    "description": "Per-inbox pricing.",
    "priority": "Tier 3",
    "free_tier": "None",
    "paid_price": "$25/mailbox/mo",
    "key_location_hint": "Dashboard"
  },
  {
    "slug": "mailwarm",
    "display_name": "Mailwarm",
    "raw_category": "Warmup",
    "category": "WARMUP",
    "homepage": "https://app.mailwarm.com/signup",
    "description": "Higher-volume warmup.",
    "priority": "Tier 3",
    "free_tier": "None",
    "paid_price": "$69/mailbox/mo",
    "key_location_hint": "Dashboard"
  },
  {
    "slug": "warmbox",
    "display_name": "Warmbox",
    "raw_category": "Warmup",
    "category": "WARMUP",
    "homepage": "https://app.warmbox.ai/register",
    "description": "Cheapest of the standalone warmups.",
    "priority": "Tier 3",
    "free_tier": "None",
    "paid_price": "$15/mailbox/mo",
    "key_location_hint": "Dashboard"
  },
  {
    "slug": "warmup_inbox",
    "display_name": "Warmup Inbox",
    "raw_category": "Warmup",
    "category": "WARMUP",
    "homepage": "https://www.warmupinbox.com/sign-up",
    "description": "Only needed if using Gmail send directly at scale. Skip if using Smartlead/Lemlist (both bundle warmup).",
    "priority": "Tier 3",
    "free_tier": "No free tier",
    "paid_price": "$19/mailbox/mo",
    "key_location_hint": "Dashboard"
  },
  {
    "slug": "warmy.io",
    "display_name": "Warmy.io",
    "raw_category": "Warmup",
    "category": "WARMUP",
    "homepage": "https://app.warmy.io/sign-up",
    "description": "AI-driven warmup.",
    "priority": "Tier 3",
    "free_tier": "7-day free",
    "paid_price": "$49/mailbox/mo",
    "key_location_hint": "Dashboard"
  },
  {
    "slug": "360dialog",
    "display_name": "360Dialog",
    "raw_category": "WhatsApp",
    "category": "WHATSAPP",
    "homepage": "https://hub.360dialog.com/registration",
    "description": "Official BSP, enterprise-friendly.",
    "priority": "Tier 3",
    "free_tier": "None",
    "paid_price": "€49/mo Starter",
    "key_location_hint": "Dashboard → API Access"
  },
  {
    "slug": "aisensy",
    "display_name": "AiSensy",
    "raw_category": "WhatsApp",
    "category": "WHATSAPP",
    "homepage": "https://www.aisensy.com/signup",
    "description": "India-focused, cheaper than Wati.",
    "priority": "Tier 3",
    "free_tier": "None",
    "paid_price": "$30/mo Basic",
    "key_location_hint": "Dashboard → API"
  },
  {
    "slug": "gallabox",
    "display_name": "Gallabox",
    "raw_category": "WhatsApp",
    "category": "WHATSAPP",
    "homepage": "https://app.gallabox.com/login",
    "description": "India, cheap.",
    "priority": "Tier 3",
    "free_tier": "None",
    "paid_price": "$20/mo Basic",
    "key_location_hint": "Dashboard → API"
  },
  {
    "slug": "interakt",
    "display_name": "Interakt",
    "raw_category": "WhatsApp",
    "category": "WHATSAPP",
    "homepage": "https://app.interakt.ai/signup",
    "description": "India-focused, full-featured.",
    "priority": "Tier 3",
    "free_tier": "None",
    "paid_price": "$19/mo Starter",
    "key_location_hint": "Dashboard → API"
  },
  {
    "slug": "messagebird_bird",
    "display_name": "MessageBird (Bird)",
    "raw_category": "WhatsApp",
    "category": "WHATSAPP",
    "homepage": "https://bird.com/signup",
    "description": "EU-friendly. Multi-channel BSP.",
    "priority": "Tier 3",
    "free_tier": "$50 free trial",
    "paid_price": "Pay per message",
    "key_location_hint": "Console → API Access"
  }
]
